sudo: false

language: php


matrix:
    include:
        - php: 7.0
    fast_finish: true

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --prefer-dist --no-interaction

notifications:
    script:
        - "phpunit --process-isolation"
    email: false
